(() => {
  'use strict';

  const CONFIG = window.IDEALAB_CONFIG || {};
  const TOKEN_KEY = 'idealab_session_token';
  const SIDEBAR_KEY = 'idealab_sidebar_collapsed';
  const VIEW_KEY = 'idealab_ideas_view';
  const STAGES = ['Idea','Planning','Execution'];
  const TASK_STATUSES = ['To Do','Doing','Blocked','Done'];
  const CRITERIA = [['interest','Interest'],['marketPotential','Market potential'],['feasibility','Feasibility'],['speedToTest','Speed to test'],['costEfficiency','Cost efficiency']];

  const state = {
    token: sessionStorage.getItem(TOKEN_KEY) || '', user:null, dashboard:{}, profiles:[], ideas:[], archive:[], ratings:[],
    currentPage:'home', currentIdea:null, currentIdeaData:null, currentTab:'overview', ideaView:localStorage.getItem(VIEW_KEY)||'board',
    dragIdeaId:'', workItems:[], workFilter:'mine', analyticsFilters:{owner:'all',stage:'all',category:'all',score:'all',flow:'all'}
  };

  const $ = id => document.getElementById(id);
  const qsa = (sel, root=document) => Array.from(root.querySelectorAll(sel));
  const one = (sel, root=document) => root.querySelector(sel);
  const els = {
    bootLoader:$('bootLoader'),loginView:$('loginView'),appView:$('appView'),loginForm:$('loginForm'),loginEmail:$('loginEmail'),loginPassword:$('loginPassword'),loginError:$('loginError'),loginButton:$('loginButton'),
    sidebar:$('sidebar'),sidebarOpen:$('sidebarOpen'),sidebarClose:$('sidebarClose'),sidebarCollapse:$('sidebarCollapse'),sidebarScrim:$('sidebarScrim'),sidebarName:$('sidebarName'),sidebarAvatar:$('sidebarAvatar'),profileMenuButton:$('profileMenuButton'),profileMenu:$('profileMenu'),openPasswordButton:$('openPasswordButton'),logoutButton:$('logoutButton'),navIdeaCount:$('navIdeaCount'),
    pageRoot:$('pageRoot'),searchButton:$('searchButton'),topAddIdea:$('topAddIdea'),toastRegion:$('toastRegion'),
    quickIdeaDialog:$('quickIdeaDialog'),quickIdeaForm:$('quickIdeaForm'),quickIdeaTitle:$('quickIdeaTitle'),quickIdeaSummary:$('quickIdeaSummary'),quickSaveIdea:$('quickSaveIdea'),quickMoreDetails:$('quickMoreDetails'),
    ideaDialog:$('ideaDialog'),ideaForm:$('ideaForm'),ideaDialogTitle:$('ideaDialogTitle'),ideaId:$('ideaId'),ideaTitle:$('ideaTitle'),ideaSummary:$('ideaSummary'),ideaStage:$('ideaStage'),ideaPriority:$('ideaPriority'),ideaOwner:$('ideaOwner'),ideaCategory:$('ideaCategory'),ideaTags:$('ideaTags'),ideaDescription:$('ideaDescription'),ideaProblem:$('ideaProblem'),ideaSolution:$('ideaSolution'),ideaTargetUser:$('ideaTargetUser'),ideaWhy:$('ideaWhy'),ideaNextAction:$('ideaNextAction'),ideaNextOwner:$('ideaNextOwner'),ideaNextDue:$('ideaNextDue'),saveIdeaButton:$('saveIdeaButton'),
    detailDialog:$('detailDialog'),ideaDetailRoot:$('ideaDetailRoot'),mediaDialog:$('mediaDialog'),mediaTitle:$('mediaTitle'),mediaPreviewRoot:$('mediaPreviewRoot'),
    searchDialog:$('searchDialog'),globalSearch:$('globalSearch'),searchResults:$('searchResults'),
    avatarDialog:$('avatarDialog'),avatarOptions:$('avatarOptions'),customAvatarInput:$('customAvatarInput'),saveCustomAvatar:$('saveCustomAvatar'),
    passwordDialog:$('passwordDialog'),passwordForm:$('passwordForm'),newPassword:$('newPassword'),confirmPassword:$('confirmPassword'),passwordError:$('passwordError'),changePasswordButton:$('changePasswordButton')
  };

  const icon = {
    bulb:'<svg viewBox="0 0 24 24"><path d="M9 18h6M10 22h4M8.5 14.5C7 13.5 6 11.8 6 9.8A6 6 0 0 1 18 9.8c0 2-1 3.7-2.5 4.7-.7.5-1 1.1-1 1.8h-5c0-.7-.3-1.3-1-1.8Z"/></svg>',
    chat:'<svg viewBox="0 0 24 24"><path d="M4 5h16v11H7l-3 3V5Z"/><path d="M8 9h8M8 12h5"/></svg>',
    search:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/></svg>',
    check:'<svg viewBox="0 0 24 24"><path d="M5 12l4 4L19 6"/></svg>',
    close:'<svg viewBox="0 0 24 24"><path d="m6 6 12 12M18 6 6 18"/></svg>',
    plus:'<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>',
    file:'<svg viewBox="0 0 24 24"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v5h5"/></svg>',
    image:'<svg viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8.5" cy="9" r="1.5"/><path d="m5 18 5-5 3 3 2-2 4 4"/></svg>'
  };

  function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function safe(v){return String(v||'').replace(/[^A-Za-z0-9_-]/g,'-');}
  function initials(v){return String(v||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();}
  function fmtDate(v,time=false){if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);return new Intl.DateTimeFormat('en-IN',time?{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'}:{day:'numeric',month:'short',year:'numeric'}).format(d);}
  function bytes(v){const n=Number(v||0);if(!n)return'';if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(n<10240?1:0)} KB`;return`${(n/1048576).toFixed(n<10485760?1:0)} MB`;}
  function avg(values){const n=values.map(Number).filter(Number.isFinite);return n.length?n.reduce((a,b)=>a+b,0)/n.length:null;}
  function round1(v){return v==null?'—':Number(v).toFixed(1);}
  function userById(id){return state.profiles.map(p=>p.user||p).find(u=>u.userId===id)||(state.user?.userId===id?state.user:null);}
  function profileName(id){const u=userById(id);return u?.displayName||u?.fullName||'Unknown';}
  function avatarFor(id){const u=userById(id);return String(u?.avatarEmoji||'').trim()||initials(u?.displayName||u?.fullName);}
  function activityAgeDays(i){const d=new Date(i.LastActivityAt||i.UpdatedAt||i.CreatedAt||0);if(Number.isNaN(d.getTime()))return 999;return Math.max(0,(Date.now()-d.getTime())/86400000);}
  function pulseClass(i){const score=combinedScore(i.IdeaID),ratings=ratingsForIdea(i.IdeaID).length,age=activityAgeDays(i);if(score!=null&&score>=8&&ratings>=Math.min(2,state.profiles.length)&&age<=7)return'pulse-hot';if((score!=null&&score>=6.5)||age<=5)return'pulse-warm';return'pulse-calm';}
  function updatedLabel(i){const d=activityAgeDays(i);if(d<1)return'Updated today';if(d<2)return'Updated yesterday';if(d<14)return`Updated ${Math.floor(d)}d ago`;return fmtDate(i.UpdatedAt||i.LastActivityAt||i.CreatedAt);}
  function workflowStatus(i){const s=String(i?.Status||'');if(s==='Completed')return'Completed';if(String(i?.Stage||'Idea')!=='Idea')return String(i?.Stage||'Idea');if(s==='Awaiting Review')return'Awaiting review';if(s==='Needs Work')return'Needs work';if(s==='Approved')return'Approved';return'Draft';}
  function workflowBucket(i){if(String(i?.Status||'')==='Completed')return'Completed';if(String(i?.Stage||'')==='Planning')return'Planning';if(String(i?.Stage||'')==='Execution')return'Execution';if(String(i?.Status||'')==='Awaiting Review')return'Review';if(String(i?.Status||'')==='Approved')return'Approved';return'Ideas';}
  function otherMember(){return state.profiles.map(p=>p.user||p).find(u=>u.userId!==state.user?.userId)||null;}
  function currentWorkflowSurface(i){return i.Stage==='Idea'?`status-surface-${safe(workflowStatus(i))}`:`stage-surface-${safe(i.Stage)}`;}
  function ratingScore(r){if(!r)return null;return avg(CRITERIA.map(([k])=>r[k]));}
  function ratingsForIdea(ideaId){return state.ratings.filter(r=>r.ideaId===ideaId);}
  function ratingFor(ideaId,userId){return state.ratings.find(r=>r.ideaId===ideaId&&r.reviewerUserId===userId);}
  function combinedScore(ideaId){return avg(ratingsForIdea(ideaId).map(ratingScore).filter(v=>v!=null));}
  function ratingGap(ideaId){const rs=ratingsForIdea(ideaId).map(ratingScore).filter(v=>v!=null);return rs.length>=2?Math.abs(rs[0]-rs[1]):null;}
  function scoreBadge(ideaId){const s=combinedScore(ideaId);return `<span class="score-badge ${s==null?'muted':''}">${s==null?'—':s.toFixed(1)}</span>`;}
  function ownerAvatar(id){const u=userById(id),color=u?.accentColor||'#5869f6';return `<span class="avatar avatar-emoji" style="background:${color}18;color:${color}">${esc(avatarFor(id))}</span>`;}
  function toast(title,message='',type='success'){const n=document.createElement('div');n.className=`toast ${type}`;n.innerHTML=`<strong>${esc(title)}</strong>${message?`<p>${esc(message)}</p>`:''}`;els.toastRegion.appendChild(n);setTimeout(()=>n.remove(),3800);}
  function busy(btn,on,label){if(!btn)return;if(on){btn.dataset.old=btn.innerHTML;btn.disabled=true;btn.textContent=label||'Working…';}else{btn.disabled=false;if(btn.dataset.old)btn.innerHTML=btn.dataset.old;delete btn.dataset.old;}}
  function hideBoot(){els.bootLoader.classList.add('fade');setTimeout(()=>els.bootLoader.hidden=true,220);}

  async function request(url,action,data={},includeToken=true){
    if(!url)throw new Error('IdeaLab backend is not configured.');
    const body={action,data};if(includeToken&&state.token)body.token=state.token;
    const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),CONFIG.REQUEST_TIMEOUT_MS||25000);
    try{
      const res=await fetch(url,{method:'POST',redirect:'follow',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body),signal:controller.signal});
      const text=await res.text();let payload;try{payload=JSON.parse(text);}catch{throw new Error('IdeaLab received an unreadable response.');}
      if(!payload.ok){const e=new Error(payload.message||'Something went wrong.');e.code=payload.error;if(['SESSION_EXPIRED','AUTH_REQUIRED'].includes(e.code))clearSession(false);throw e;}return payload;
    }catch(e){if(e.name==='AbortError')throw new Error('The request took too long. Please try again.');throw e;}finally{clearTimeout(timer);}
  }
  const api=(action,data={})=>request(CONFIG.API_URL,action,data,action!=='login');
  const insights=(action,data={})=>request(CONFIG.INSIGHTS_API_URL,action,data,true);

  function saveToken(token){state.token=token||'';if(state.token)sessionStorage.setItem(TOKEN_KEY,state.token);else sessionStorage.removeItem(TOKEN_KEY);}
  function clearSession(show=true){saveToken('');state.user=null;state.dashboard={};state.profiles=[];state.ideas=[];state.ratings=[];if(show)showLogin();}
  function showLogin(){els.appView.hidden=true;els.loginView.hidden=false;closeSidebar();hideBoot();setTimeout(()=>els.loginEmail.focus(),50);}
  function showApp(){els.loginView.hidden=true;els.appView.hidden=false;hydrateProfile();hideBoot();}

  function hydrateProfile(){
    if(!state.user)return;const c=state.user.accentColor||'#5869f6';els.sidebarName.textContent=state.user.displayName||state.user.fullName||'Profile';els.sidebarAvatar.textContent=String(state.user.avatarEmoji||'').trim()||initials(state.user.displayName||state.user.fullName);els.sidebarAvatar.classList.toggle('avatar-emoji',Boolean(String(state.user.avatarEmoji||'').trim()));els.sidebarAvatar.style.background=`${c}18`;els.sidebarAvatar.style.color=c;els.navIdeaCount.textContent=state.ideas.length;
    const opts=state.profiles.map(p=>{const u=p.user||p;return`<option value="${esc(u.userId)}">${esc(u.displayName||u.fullName)}</option>`}).join('');els.ideaOwner.innerHTML=opts;els.ideaNextOwner.innerHTML=`<option value="">Not assigned</option>${opts}`;
  }

  async function loadState(){
    const app=await api('getAppState');state.user=app.user;state.dashboard=app.dashboard||{};state.profiles=app.profiles||[];state.ideas=app.ideas||[];
    try{const r=await insights('listRatings');state.ratings=r.ratings||[];}catch(e){state.ratings=[];console.warn('Ratings unavailable',e.message);}
    try{const a=await insights('listAvatars'),map=new Map((a.avatars||[]).map(x=>[x.userId,x.avatarEmoji||'']));state.profiles.forEach(p=>{const u=p.user||p;u.avatarEmoji=map.get(u.userId)||'';});const mine=state.profiles.map(p=>p.user||p).find(u=>u.userId===state.user.userId);if(mine)state.user.avatarEmoji=mine.avatarEmoji||'';}catch(e){console.warn('Avatars unavailable',e.message);}
    hydrateProfile();
  }
  async function refresh(render=true){await loadState();if(render)renderCurrent();}

  async function login(e){e.preventDefault();els.loginError.hidden=true;busy(els.loginButton,true,'Signing in…');try{const p=await api('login',{email:els.loginEmail.value.trim(),password:els.loginPassword.value});saveToken(p.token);state.user=p.user;await loadState();showApp();navigate('home');}catch(err){els.loginError.textContent=err.message;els.loginError.hidden=false;}finally{busy(els.loginButton,false);}}
  async function logout(){try{if(state.token)await api('logout');}catch{}clearSession(true);}
  async function changePassword(e){e.preventDefault();els.passwordError.hidden=true;const p=els.newPassword.value;if(p!==els.confirmPassword.value){els.passwordError.textContent='The passwords do not match.';els.passwordError.hidden=false;return;}if(p.length<10){els.passwordError.textContent='Use at least 10 characters.';els.passwordError.hidden=false;return;}busy(els.changePasswordButton,true,'Saving…');try{const r=await api('changePassword',{newPassword:p});if(r.token)saveToken(r.token);els.passwordDialog.close();toast('Password updated');}catch(err){els.passwordError.textContent=err.message;els.passwordError.hidden=false;}finally{busy(els.changePasswordButton,false);}}

  function setSidebarCollapsed(collapsed,persist=false){document.body.classList.toggle('sidebar-collapsed',Boolean(collapsed));if(els.sidebarCollapse){els.sidebarCollapse.setAttribute('aria-expanded',String(!collapsed));els.sidebarCollapse.setAttribute('aria-label',collapsed?'Expand navigation':'Collapse navigation');const p=els.sidebarCollapse.querySelector('path');if(p)p.setAttribute('d',collapsed?'m10 7 5 5-5 5':'m14 7-5 5 5 5');}if(persist)localStorage.setItem(SIDEBAR_KEY,collapsed?'1':'0');}
  function toggleSidebar(){setSidebarCollapsed(!document.body.classList.contains('sidebar-collapsed'),true);}
  function openSidebar(){els.sidebar.classList.add('mobile-open');els.sidebarScrim.hidden=false;}
  function closeSidebar(){els.sidebar.classList.remove('mobile-open');els.sidebarScrim.hidden=true;}

  function navigate(page){state.currentPage=page;qsa('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===page));renderCurrent();closeSidebar();els.profileMenu.hidden=true;window.scrollTo({top:0,behavior:'smooth'});}
  function renderCurrent(){if(!state.user)return;const page=state.currentPage;if(page==='home')renderHome();else if(page==='ideas')renderIdeas();else if(page==='mywork')renderMyWork();else if(['planning','execution'].includes(page))renderStage(page);else if(page==='reviews')renderReviews();else if(page==='analytics')renderAnalytics();else if(page==='archive')renderArchive();else if(page==='profiles')renderProfiles();else renderHome();}
  function wrap(html){els.pageRoot.innerHTML=`<section class="page-section">${html}</section>`;bindRendered(els.pageRoot);}
  function metric(cls,iconHtml,val,label){return`<article class="metric-card ${cls}"><div class="metric-icon">${iconHtml}</div><strong>${esc(val)}</strong><p>${esc(label)}</p></article>`;}
  function empty(title,text,button='',nav=''){return`<div class="empty-state"><div><h3>${esc(title)}</h3><p>${esc(text)}</p>${button?`<button class="button button-primary" ${nav?`data-nav-inline="${esc(nav)}"`:'data-new-idea'}>${esc(button)}</button>`:''}</div></div>`;}

  function ideaRow(i){const u=userById(i.OwnerUserID),color=u?.accentColor||'#5869f6';return`<button class="idea-list-row" data-open-idea="${esc(i.IdeaID)}"><span class="owner-stripe" style="--owner-color:${color}"></span><span class="idea-list-copy"><strong>${esc(i.Title)}</strong><p>${esc(i.OneLineSummary||i.Description||'No description')}</p></span><span class="idea-list-meta">${scoreBadge(i.IdeaID)}<span class="stage-chip stage-${safe(i.Stage)}">${esc(workflowStatus(i))}</span></span></button>`;}
  function ideaCard(i){const u=userById(i.OwnerUserID),color=u?.accentColor||'#5869f6',score=combinedScore(i.IdeaID),tags=String(i.Tags||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,2);return`<article class="idea-card ${currentWorkflowSurface(i)} ${pulseClass(i)}" draggable="false" data-open-idea="${esc(i.IdeaID)}" style="--owner-color:${color}"><div class="idea-card-stage"><span>${esc(workflowStatus(i))}</span><span class="idea-score-orb ${score==null?'empty':''}"><strong>${score==null?'—':score.toFixed(1)}</strong></span></div><h4>${esc(i.Title)}</h4><p>${esc(i.OneLineSummary||i.Description||'No summary')}</p>${tags.length?`<div class="idea-tags">${tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div>`:''}<div class="idea-card-foot"><span class="owner-mini">${ownerAvatar(i.OwnerUserID)}${esc(u?.displayName||'Unknown')}</span><small>${esc(updatedLabel(i))}</small></div></article>`;}

  function renderHome(){
    const avgScore=avg(state.ideas.map(i=>combinedScore(i.IdeaID)).filter(v=>v!=null)),rated=state.ideas.filter(i=>ratingsForIdea(i.IdeaID).length>0).length;
    const focus=[...state.ideas].sort((a,b)=>{const sa=combinedScore(a.IdeaID)??-1,sb=combinedScore(b.IdeaID)??-1;if(sb!==sa)return sb-sa;return activityAgeDays(a)-activityAgeDays(b);}).slice(0,3);
    const recent=[...state.ideas].sort((a,b)=>String(b.LastActivityAt||b.UpdatedAt||'').localeCompare(String(a.LastActivityAt||a.UpdatedAt||''))).slice(0,6);
    wrap(`<section class="focus-section"><div class="focus-head"><div><span>Current focus</span><h2>Ideas with momentum</h2></div><button class="text-button" data-nav-inline="ideas">All ideas</button></div>${focus.length?`<div class="focus-grid">${focus.map(i=>ideaCard(i)).join('')}</div>`:empty('No ideas yet','Use the + button to add the first idea.')}</section><div class="metric-grid metric-grid-compact">${metric('primary',icon.bulb,state.ideas.length,'Active ideas')}${metric('pink',icon.chat,rated,'Rated')}${metric('amber',icon.search,avgScore==null?'—':avgScore.toFixed(1),'Average score')}${metric('green',icon.check,state.ideas.filter(i=>i.Stage==='Execution').length,'Execution')}</div><section class="recent-section"><div class="section-simple-head"><h3>Recent ideas</h3></div>${recent.length?`<div class="idea-list clean-list">${recent.map(ideaRow).join('')}</div>`:''}</section>`);
  }

  function ideaStatusColumn(title,ideas){return`<section class="board-column board-status-${safe(title)}"><div class="board-column-head"><h3>${esc(title)}</h3><span class="column-count">${ideas.length}</span></div><div class="board-cards">${ideas.length?ideas.map(ideaCard).join(''):'<div class="empty-column">No ideas</div>'}</div></section>`;}
  function renderIdeas(){if(state.ideaView==='ranked')return renderRanked();const rows=state.ideas.filter(i=>i.Stage==='Idea'&&i.Status!=='Completed');const draft=rows.filter(i=>!['Awaiting Review','Needs Work','Approved'].includes(String(i.Status||''))),review=rows.filter(i=>i.Status==='Awaiting Review'),needs=rows.filter(i=>i.Status==='Needs Work'),approved=rows.filter(i=>i.Status==='Approved');wrap(`<div class="board-toolbar"><div class="view-toggle"><button class="active" data-idea-view="board">Board</button><button data-idea-view="ranked">Ranked</button></div><div class="board-spacer"></div><span class="board-hint">Review before planning</span></div><div class="board idea-review-board">${ideaStatusColumn('Draft',draft)}${ideaStatusColumn('Awaiting review',review)}${ideaStatusColumn('Needs work',needs)}${ideaStatusColumn('Approved',approved)}</div>`);}
  function rankedRows(ideas=state.ideas){return [...ideas].sort((a,b)=>(combinedScore(b.IdeaID)??-1)-(combinedScore(a.IdeaID)??-1));}
  function renderRanked(){const users=state.profiles.map(p=>p.user||p),rows=rankedRows(state.ideas.filter(i=>i.Stage==='Idea'&&i.Status!=='Completed'));wrap(`<div class="board-toolbar"><div class="view-toggle"><button data-idea-view="board">Board</button><button class="active" data-idea-view="ranked">Ranked</button></div><div class="board-spacer"></div><span class="pill">${rows.length} ideas</span></div><div class="panel table-wrap"><table class="data-table"><thead><tr><th>#</th><th>Idea</th><th>Status</th><th>Owner</th>${users.map(u=>`<th>${esc(u.displayName)} score</th>`).join('')}<th>Combined</th><th>Category</th></tr></thead><tbody>${rows.map((i,idx)=>`<tr data-open-idea="${esc(i.IdeaID)}"><td class="rank-number">${idx+1}</td><td><strong>${esc(i.Title)}</strong></td><td><span class="stage-chip">${esc(workflowStatus(i))}</span></td><td>${esc(profileName(i.OwnerUserID))}</td>${users.map(u=>`<td>${round1(ratingScore(ratingFor(i.IdeaID,u.userId)))}</td>`).join('')}<td><strong>${round1(combinedScore(i.IdeaID))}</strong></td><td>${esc(i.Category||'—')}</td></tr>`).join('')}</tbody></table></div>`);}
  function renderStage(page){const stage={planning:'Planning',execution:'Execution'}[page],rows=state.ideas.filter(i=>i.Stage===stage);wrap(`<div class="board-toolbar"><span class="pill">${rows.length} ideas</span></div>${rows.length?`<div class="lifecycle-grid">${rows.map(ideaCard).join('')}</div>`:empty('No ideas here',stage==='Planning'?'Approved ideas can be moved here from Ideas.':'Planning ideas can be started when you are ready to execute.')}`);}

  function renderMyWork(){const other=otherMember();wrap(`<div class="work-toolbar"><div><span class="eyebrow">Responsibilities</span><h2>My Work</h2></div><div class="view-toggle work-toggle"><button class="${state.workFilter==='mine'?'active':''}" data-work-filter="mine">Mine</button>${other?`<button class="${state.workFilter==='other'?'active':''}" data-work-filter="other">${esc(other.displayName||other.fullName)}</button>`:''}<button class="${state.workFilter==='all'?'active':''}" data-work-filter="all">All</button></div></div><div id="workRoot" class="work-root"><div class="work-loading">Loading responsibilities…</div></div>`);qsa('[data-work-filter]',els.pageRoot).forEach(b=>b.addEventListener('click',()=>{state.workFilter=b.dataset.workFilter;renderMyWork();}));loadMyWork();}
  async function loadMyWork(){const root=$('workRoot');if(!root)return;try{const p=await insights('listWork');state.workItems=p.items||[];drawMyWork();}catch(e){root.innerHTML=empty('Could not load responsibilities',e.message);}}
  function drawMyWork(){const root=$('workRoot');if(!root)return;const other=otherMember(),assignee=state.workFilter==='mine'?state.user.userId:state.workFilter==='other'?other?.userId:null;let items=state.workItems.filter(x=>!assignee||x.assigneeUserId===assignee);const today=new Date();today.setHours(0,0,0,0);const week=today.getTime()+7*86400000;const due=x=>{const d=new Date(x.dueDate||'');return Number.isNaN(d.getTime())?0:d.getTime();};const groups=[['Pending reviews',items.filter(x=>x.type==='review')],['Overdue',items.filter(x=>x.type!=='review'&&due(x)&&due(x)<today.getTime())],['Due this week',items.filter(x=>x.type!=='review'&&due(x)>=today.getTime()&&due(x)<=week)],['Later',items.filter(x=>x.type!=='review'&&due(x)>week)],['No due date',items.filter(x=>x.type!=='review'&&!due(x))]].filter(([,r])=>r.length);const overdue=items.filter(x=>x.type!=='review'&&due(x)&&due(x)<today.getTime()).length,reviews=items.filter(x=>x.type==='review').length;root.innerHTML=`<div class="work-summary"><div><strong>${items.length}</strong><span>Open</span></div><div><strong>${reviews}</strong><span>Reviews</span></div><div><strong>${overdue}</strong><span>Overdue</span></div></div>${groups.length?groups.map(([title,rows])=>`<section class="work-group"><h3>${esc(title)}</h3><div class="work-list">${rows.map(x=>`<article class="work-item ${x.type==='review'?'review-work':''}"><div class="work-item-main"><span class="work-type">${esc(x.type==='review'?'Review':x.type==='task'?'Task':'Idea')}</span><strong>${esc(x.title)}</strong><p>${esc(x.ideaTitle)} · ${esc(x.ideaStage||'Idea')}</p></div><div class="work-item-meta">${x.dueDate?`<span>${esc(fmtDate(x.dueDate))}</span>`:''}<span class="pill">${esc(x.status||'Open')}</span><button class="button button-secondary button-small" data-work-open="${esc(x.ideaId)}" data-work-tab="${x.type==='review'?'rating':x.ideaStage==='Execution'?'execution':x.ideaStage==='Planning'?'planning':'overview'}">${x.type==='review'?'Review':'Open'}</button>${x.type==='task'?`<button class="button button-primary button-small" data-work-done="${esc(x.id)}">Done</button>`:''}</div></article>`).join('')}</div></section>`).join(''):empty('Nothing pending','No open responsibilities in this view.')}`;qsa('[data-work-open]',root).forEach(b=>b.addEventListener('click',()=>openIdea(b.dataset.workOpen,b.dataset.workTab||'overview')));qsa('[data-work-done]',root).forEach(b=>b.addEventListener('click',()=>completeWorkTask(b.dataset.workDone)));}
  async function completeWorkTask(taskId){try{await api('updateTask',{taskId,status:'Done'});toast('Task completed');await loadMyWork();}catch(e){toast('Could not update task',e.message,'error');}}

  function bindBoardDnD(){qsa('[data-drag-idea]',els.pageRoot).forEach(card=>{card.addEventListener('dragstart',e=>{state.dragIdeaId=card.dataset.dragIdea;card.classList.add('dragging');e.dataTransfer.effectAllowed='move';});card.addEventListener('dragend',()=>{card.classList.remove('dragging');qsa('.board-column').forEach(c=>c.classList.remove('drag-over'));state.dragIdeaId='';});});qsa('[data-drop-stage]',els.pageRoot).forEach(col=>{col.addEventListener('dragover',e=>{e.preventDefault();col.classList.add('drag-over');e.dataTransfer.dropEffect='move';});col.addEventListener('dragleave',()=>col.classList.remove('drag-over'));col.addEventListener('drop',async e=>{e.preventDefault();col.classList.remove('drag-over');const id=state.dragIdeaId,stage=col.dataset.dropStage,idea=state.ideas.find(i=>i.IdeaID===id);if(!idea||idea.Stage===stage)return;const old=idea.Stage;idea.Stage=stage;renderIdeas();try{await api('updateIdea',{ideaId:id,stage});toast('Stage updated');}catch(err){idea.Stage=old;renderIdeas();toast('Could not move idea',err.message,'error');}});});}

  function renderReviews(){
    const gaps=state.ideas.map(i=>({idea:i,gap:ratingGap(i.IdeaID),score:combinedScore(i.IdeaID)})).filter(x=>x.gap!=null).sort((a,b)=>b.gap-a.gap).slice(0,6),unrated=state.ideas.filter(i=>ratingsForIdea(i.IdeaID).length<state.profiles.length).slice(0,6);
    wrap(`<div class="review-grid"><div><div class="review-card"><div style="display:flex;align-items:center;justify-content:space-between;gap:10px"><h3 style="margin:0">Review sessions</h3><button id="newReviewBtn" class="button button-primary button-small">${icon.plus} Start review</button></div><div id="reviewSessions"><p style="color:var(--faint);font-size:10px">Loading…</p></div></div><div class="review-card" style="margin-top:14px"><h3>Largest rating gaps</h3>${gaps.length?gaps.map(x=>`<div class="review-session" data-open-idea="${esc(x.idea.IdeaID)}"><span><strong>${esc(x.idea.Title)}</strong><small>Combined ${round1(x.score)}</small></span><span class="score-badge">${x.gap.toFixed(1)} gap</span></div>`).join(''):'<p style="color:var(--faint);font-size:10px">No paired ratings yet.</p>'}</div></div><aside class="review-card"><h3>Needs a rating</h3>${unrated.length?unrated.map(i=>`<div class="review-session" data-open-idea="${esc(i.IdeaID)}"><span><strong>${esc(i.Title)}</strong><small>${ratingsForIdea(i.IdeaID).length}/${state.profiles.length} rated</small></span><span class="stage-chip stage-${safe(i.Stage)}">${esc(i.Stage)}</span></div>`).join(''):'<p style="color:var(--faint);font-size:10px">All active ideas are rated.</p>'}</aside></div>`);$('newReviewBtn')?.addEventListener('click',createReview);loadReviews();}
  async function loadReviews(){const root=$('reviewSessions');if(!root)return;try{const p=await api('listReviewSessions'),rows=(p.reviewSessions||[]).slice().reverse().slice(0,10);root.innerHTML=rows.length?rows.map(r=>`<div class="review-session"><span><strong>${esc(r.Title)}</strong><small>${esc(r.Status)} · ${esc(r.ReviewDate)}</small></span><span class="pill">${esc(r.CreatedByUserID===state.user.userId?'You':'Shared')}</span></div>`).join(''):'<p style="color:var(--faint);font-size:10px;margin-top:12px">No review sessions yet.</p>';}catch(e){root.innerHTML=`<p style="color:var(--red);font-size:10px">${esc(e.message)}</p>`;}}
  async function createReview(){const b=$('newReviewBtn');busy(b,true,'Creating…');try{await api('createReviewSession',{});await loadReviews();toast('Review created');}catch(e){toast('Could not create review',e.message,'error');}finally{busy(b,false);}}

  function analyticsIdeas(){return state.ideas.filter(i=>{const f=state.analyticsFilters;if(f.owner!=='all'&&i.OwnerUserID!==f.owner)return false;if(f.stage!=='all'&&i.Stage!==f.stage)return false;if(f.flow!=='all'&&workflowBucket(i)!==f.flow)return false;if(f.category!=='all'&&String(i.Category||'')!==f.category)return false;const s=combinedScore(i.IdeaID);if(f.score==='rated'&&s==null)return false;if(f.score==='8+'&&(s==null||s<8))return false;if(f.score==='6-8'&&(s==null||s<6||s>=8))return false;if(f.score==='<6'&&(s==null||s>=6))return false;if(f.score==='unrated'&&s!=null)return false;return true;});}
  function analyticsFilterBar(){const cats=[...new Set(state.ideas.map(i=>String(i.Category||'').trim()).filter(Boolean))].sort();return`<div class="analytics-filters"><select id="analyticsOwner"><option value="all">All owners</option>${state.profiles.map(p=>{const u=p.user||p;return`<option value="${esc(u.userId)}" ${state.analyticsFilters.owner===u.userId?'selected':''}>${esc(u.displayName||u.fullName)}</option>`}).join('')}</select><select id="analyticsStage"><option value="all">All stages</option>${STAGES.map(s=>`<option ${state.analyticsFilters.stage===s?'selected':''}>${s}</option>`).join('')}</select><select id="analyticsCategory"><option value="all">All categories</option>${cats.map(c=>`<option ${state.analyticsFilters.category===c?'selected':''}>${esc(c)}</option>`).join('')}</select><select id="analyticsScore"><option value="all">All scores</option><option value="rated" ${state.analyticsFilters.score==='rated'?'selected':''}>Rated only</option><option value="8+" ${state.analyticsFilters.score==='8+'?'selected':''}>8.0+</option><option value="6-8" ${state.analyticsFilters.score==='6-8'?'selected':''}>6.0–7.9</option><option value="<6" ${state.analyticsFilters.score==='<6'?'selected':''}>Below 6</option><option value="unrated" ${state.analyticsFilters.score==='unrated'?'selected':''}>Unrated</option></select><div class="analytics-actions"><button id="exportCsv" class="button button-secondary button-small">Export CSV</button><button id="exportExcel" class="button button-secondary button-small">Export Excel</button></div></div>`;}
  function pipelineHTML(ideas){const steps=['Ideas','Review','Approved','Planning','Execution','Completed'];return`<div class="pipeline">${steps.map(s=>{const n=ideas.filter(i=>workflowBucket(i)===s).length,pct=ideas.length?Math.round(n/ideas.length*100):0;return`<button class="pipeline-step" data-analytics-flow="${esc(s)}"><strong>${n}</strong><span>${esc(s==='Review'?'Awaiting review':s)}</span><small>${pct}%</small></button>`}).join('')}</div>`;}
  function topBars(ideas){const rows=rankedRows(ideas).filter(i=>combinedScore(i.IdeaID)!=null).slice(0,7);if(!rows.length)return'<p style="color:var(--faint);font-size:10px">No ratings in this view.</p>';return`<div class="bar-list">${rows.map(i=>{const s=combinedScore(i.IdeaID);return`<div class="bar-row" data-open-idea="${esc(i.IdeaID)}" style="cursor:pointer"><span class="bar-label">${esc(i.Title)}</span><span class="bar-track"><span class="bar-fill" style="width:${Math.max(0,Math.min(100,s*10))}%"></span></span><span class="bar-value">${s.toFixed(1)}</span></div>`}).join('')}</div>`;}
  function distributionHTML(ideas){const buckets=[['8–10',8,10.01],['6–7.9',6,8],['4–5.9',4,6],['Below 4',0,4]],vals=ideas.map(i=>combinedScore(i.IdeaID)).filter(v=>v!=null),max=Math.max(1,...buckets.map(([,lo,hi])=>vals.filter(v=>v>=lo&&v<hi).length));return buckets.map(([label,lo,hi])=>{const n=vals.filter(v=>v>=lo&&v<hi).length;return`<div class="distribution-row"><span>${label}</span><span class="bar-track"><span class="bar-fill" style="width:${n/max*100}%"></span></span><strong>${n}</strong></div>`}).join('');}
  function scatterHTML(ideas){const users=state.profiles.map(p=>p.user||p).slice(0,2);if(users.length<2)return'<p style="color:var(--faint);font-size:10px">Two profiles are required.</p>';const points=ideas.map(i=>({i,a:ratingScore(ratingFor(i.IdeaID,users[0].userId)),b:ratingScore(ratingFor(i.IdeaID,users[1].userId))})).filter(x=>x.a!=null&&x.b!=null);if(!points.length)return'<p style="color:var(--faint);font-size:10px">No paired ratings in this view.</p>';const x=v=>28+(v-1)/9*310,y=v=>215-(v-1)/9*185;return`<div class="scatter-wrap"><svg class="scatter" viewBox="0 0 370 240" role="img" aria-label="Rating comparison"><line class="axis" x1="28" y1="215" x2="348" y2="215"/><line class="axis" x1="28" y1="215" x2="28" y2="20"/><line class="guide" x1="28" y1="215" x2="348" y2="20"/><text x="270" y="235">${esc(users[0].displayName)}</text><text x="5" y="18">${esc(users[1].displayName)}</text>${points.map(p=>`<circle cx="${x(p.a)}" cy="${y(p.b)}" r="5" data-svg-idea="${esc(p.i.IdeaID)}"><title>${esc(p.i.Title)}: ${p.a.toFixed(1)} / ${p.b.toFixed(1)}</title></circle>`).join('')}</svg></div>`;}
  function timelineHTML(ideas){const groups={};ideas.forEach(i=>{const d=new Date(i.CreatedAt);if(Number.isNaN(d.getTime()))return;const k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;groups[k]=(groups[k]||0)+1;});const keys=Object.keys(groups).sort().slice(-8);if(!keys.length)return'<p style="color:var(--faint);font-size:10px">No creation dates available.</p>';const vals=keys.map(k=>groups[k]),max=Math.max(1,...vals),x=idx=>20+(keys.length===1?0:idx/(keys.length-1)*330),y=v=>150-v/max*115,pts=vals.map((v,i)=>`${x(i)},${y(v)}`).join(' '),area=`20,160 ${pts} ${x(keys.length-1)},160`;return`<svg class="timeline-svg" viewBox="0 0 370 180"><polygon class="timeline-area" points="${area}"/><polyline class="timeline-line" points="${pts}"/>${vals.map((v,i)=>`<circle class="timeline-dot" cx="${x(i)}" cy="${y(v)}" r="4"><title>${keys[i]}: ${v}</title></circle><text x="${x(i)}" y="174" text-anchor="middle" style="font:8px var(--font);fill:var(--faint)">${keys[i].slice(5)}</text>`).join('')}</svg>`;}
  function categoryBars(ideas){const map={};ideas.forEach(i=>{const c=String(i.Category||'Uncategorised'),s=combinedScore(i.IdeaID);if(!map[c])map[c]={count:0,scores:[]};map[c].count++;if(s!=null)map[c].scores.push(s);});const rows=Object.entries(map).map(([c,v])=>({c,count:v.count,score:avg(v.scores)})).sort((a,b)=>(b.score??-1)-(a.score??-1)).slice(0,7);return rows.length?`<div class="bar-list">${rows.map(r=>`<div class="bar-row"><span class="bar-label">${esc(r.c)} (${r.count})</span><span class="bar-track"><span class="bar-fill" style="width:${(r.score||0)*10}%"></span></span><span class="bar-value">${round1(r.score)}</span></div>`).join('')}</div>`:'<p style="color:var(--faint);font-size:10px">No categories.</p>';}
  function analyticsTable(ideas){const users=state.profiles.map(p=>p.user||p),rows=rankedRows(ideas);return`<div class="table-wrap"><table class="data-table"><thead><tr><th>Idea</th><th>Owner</th><th>Stage</th>${users.map(u=>`<th>${esc(u.displayName)}</th>`).join('')}<th>Combined</th><th>Category</th><th>Priority</th><th>Updated</th></tr></thead><tbody>${rows.map(i=>`<tr data-open-idea="${esc(i.IdeaID)}"><td><strong>${esc(i.Title)}</strong></td><td>${esc(profileName(i.OwnerUserID))}</td><td>${esc(i.Stage)}</td>${users.map(u=>`<td>${round1(ratingScore(ratingFor(i.IdeaID,u.userId)))}</td>`).join('')}<td><strong>${round1(combinedScore(i.IdeaID))}</strong></td><td>${esc(i.Category||'—')}</td><td>${esc(i.Priority||'—')}</td><td>${esc(fmtDate(i.UpdatedAt||i.CreatedAt))}</td></tr>`).join('')}</tbody></table></div>`;}
  function renderAnalytics(){const ideas=analyticsIdeas(),scores=ideas.map(i=>combinedScore(i.IdeaID)).filter(v=>v!=null),paired=ideas.filter(i=>ratingsForIdea(i.IdeaID).length>=2),gaps=paired.map(i=>({i,g:ratingGap(i.IdeaID)})).sort((a,b)=>b.g-a.g).slice(0,5);wrap(`<div class="analytics-hero"><div class="analytics-hero-top"><div><span>Analytics</span><h2>Idea pipeline</h2></div>${analyticsFilterBar()}</div>${pipelineHTML(ideas)}<div class="analytics-hero-stats"><div><strong>${ideas.length}</strong><span>Ideas</span></div><div><strong>${scores.length}</strong><span>Rated</span></div><div><strong>${scores.length?avg(scores).toFixed(1):'—'}</strong><span>Average score</span></div><div><strong>${ideas.filter(i=>i.Stage==='Execution').length}</strong><span>Execution</span></div></div></div><div class="analytics-grid"><section class="analytics-card"><h3>Top rated</h3>${topBars(ideas)}</section><section class="analytics-card"><h3>Score distribution</h3>${distributionHTML(ideas)}</section><section class="analytics-card"><h3>Rating comparison</h3>${scatterHTML(ideas)}</section><section class="analytics-card"><h3>Largest disagreements</h3>${gaps.length?`<div class="disagreement-list">${gaps.map(x=>`<div class="disagreement-item" data-open-idea="${esc(x.i.IdeaID)}"><strong>${esc(x.i.Title)}</strong><span class="score-badge">${x.g.toFixed(1)}</span></div>`).join('')}</div>`:'<p style="color:var(--faint);font-size:10px">No paired ratings.</p>'}</section><section class="analytics-card"><h3>Ideas created</h3>${timelineHTML(ideas)}</section><section class="analytics-card"><h3>Category performance</h3>${categoryBars(ideas)}</section><section class="analytics-card full"><h3>Ranked ideas</h3>${analyticsTable(ideas)}</section></div>`);bindAnalytics();}
  function bindAnalytics(){['Owner','Stage','Category','Score'].forEach(k=>{const el=$(`analytics${k}`);el?.addEventListener('change',()=>{state.analyticsFilters[k.toLowerCase()]=el.value;if(k==='Stage')state.analyticsFilters.flow='all';renderAnalytics();});});$('exportCsv')?.addEventListener('click',()=>exportAnalytics('csv'));$('exportExcel')?.addEventListener('click',()=>exportAnalytics('excel'));qsa('[data-analytics-flow]',els.pageRoot).forEach(x=>x.addEventListener('click',()=>{state.analyticsFilters.flow=x.dataset.analyticsFlow;state.analyticsFilters.stage='all';renderAnalytics();}));qsa('[data-svg-idea]',els.pageRoot).forEach(x=>x.addEventListener('click',()=>openIdea(x.dataset.svgIdea)));}
  function exportRows(){const ideas=analyticsIdeas(),users=state.profiles.map(p=>p.user||p);return{headers:['Idea','Owner','Stage','Status',...users.map(u=>`${u.displayName} score`),'Combined score','Category','Priority','Created','Updated'],rows:rankedRows(ideas).map(i=>[i.Title,profileName(i.OwnerUserID),i.Stage,workflowStatus(i),...users.map(u=>round1(ratingScore(ratingFor(i.IdeaID,u.userId)))),round1(combinedScore(i.IdeaID)),i.Category||'',i.Priority||'',i.CreatedAt||'',i.UpdatedAt||''])};}
  function downloadBlob(content,type,name){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500);}
  function exportAnalytics(type){const {headers,rows}=exportRows(),stamp=new Date().toISOString().slice(0,10);if(type==='csv'){const csv=[headers,...rows].map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\r\n');downloadBlob('\ufeff'+csv,'text/csv;charset=utf-8',`IdeaLab-Analytics-${stamp}.csv`);return;}const escXml=v=>String(v??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Analytics"><Table>${[headers,...rows].map(r=>`<Row>${r.map(v=>`<Cell><Data ss:Type="String">${escXml(v)}</Data></Cell>`).join('')}</Row>`).join('')}</Table></Worksheet></Workbook>`;downloadBlob(xml,'application/vnd.ms-excel',`IdeaLab-Analytics-${stamp}.xml`);}

  async function renderArchive(){wrap('<div id="archiveRoot"><div class="empty-state"><div><p>Loading…</p></div></div></div>');const root=$('archiveRoot');try{const p=await api('listIdeas',{status:'Archived'});state.archive=p.ideas||[];root.innerHTML=state.archive.length?`<div class="panel"><div class="idea-list">${state.archive.map(ideaRow).join('')}</div></div>`:empty('No archived ideas','Archived ideas will appear here.');bindRendered(root);}catch(e){root.innerHTML=empty('Could not load archive',e.message);}}
  function renderProfiles(){wrap(`<div class="profile-grid">${state.profiles.map(p=>{const u=p.user||p,s=p.stats||{},c=u.accentColor||'#5869f6',mine=u.userId===state.user.userId;return`<article class="profile-card studio-profile-card"><div class="profile-hero"><span class="avatar profile-avatar ${u.avatarEmoji?'avatar-emoji':''}" style="background:${c}18;color:${c}">${esc(String(u.avatarEmoji||'').trim()||initials(u.displayName||u.fullName))}</span><span><h3>${esc(u.displayName||u.fullName)}</h3><p>${esc(u.email||'')}</p></span>${mine?`<button class="button button-secondary button-small profile-avatar-button" data-change-avatar>Change avatar</button>`:''}</div><div class="profile-stats"><div class="profile-stat"><strong>${s.ideasSubmitted||0}</strong><span>Ideas</span></div><div class="profile-stat"><strong>${s.activeIdeas||0}</strong><span>Active</span></div><div class="profile-stat"><strong>${s.brainstormNotes||0}</strong><span>Notes</span></div><div class="profile-stat"><strong>${s.experimentsOwned||0}</strong><span>Experiments</span></div><div class="profile-stat"><strong>${s.openTasks||0}</strong><span>Open tasks</span></div><div class="profile-stat"><strong>${state.ratings.filter(r=>r.reviewerUserId===u.userId).length}</strong><span>Ratings</span></div></div></article>`}).join('')}</div>`);}

  const AVATAR_OPTIONS=['🧠','💡','🚀','🧑‍💻','👩‍💻','🎯','🦊','🐼','🌙','⭐','🪐','🎨','📚','☕','🔥','🌿'];
  function openAvatarPicker(){els.avatarOptions.innerHTML=AVATAR_OPTIONS.map(a=>`<button type="button" class="avatar-option" data-avatar-choice="${a}">${a}</button>`).join('');els.customAvatarInput.value=String(state.user.avatarEmoji||'');qsa('[data-avatar-choice]',els.avatarOptions).forEach(b=>b.addEventListener('click',()=>saveAvatar(b.dataset.avatarChoice)));els.avatarDialog.showModal();}
  async function saveAvatar(value){const emoji=String(value||'').trim();busy(els.saveCustomAvatar,true,'Saving…');try{const p=await insights('saveAvatar',{avatarEmoji:emoji});state.user.avatarEmoji=p.avatarEmoji||'';state.profiles.forEach(x=>{const u=x.user||x;if(u.userId===state.user.userId)u.avatarEmoji=p.avatarEmoji||'';});els.avatarDialog.close();hydrateProfile();renderCurrent();toast('Avatar updated');}catch(e){toast('Could not update avatar',e.message,'error');}finally{busy(els.saveCustomAvatar,false);}}

  function openQuickIdea(){els.quickIdeaForm.reset();els.quickIdeaDialog.showModal();setTimeout(()=>els.quickIdeaTitle.focus(),40);}
  async function saveQuickIdea(e){e.preventDefault();const title=els.quickIdeaTitle.value.trim();if(!title)return;busy(els.quickSaveIdea,true,'Saving…');try{const p=await api('createIdea',{title,oneLineSummary:els.quickIdeaSummary.value.trim(),ownerUserId:state.user.userId,stage:'Idea',status:'Draft',priority:'Medium'});els.quickIdeaDialog.close();await refresh();toast('Idea saved');if(p.idea?.IdeaID)openIdea(p.idea.IdeaID,'rating');}catch(err){toast('Could not save idea',err.message,'error');}finally{busy(els.quickSaveIdea,false);}}
  function quickToDetails(){const draft={Title:els.quickIdeaTitle.value.trim(),OneLineSummary:els.quickIdeaSummary.value.trim(),OwnerUserID:state.user.userId,Stage:'Idea',Status:'Draft',Priority:'Medium'};els.quickIdeaDialog.close();openIdeaForm(draft,false);}
  function openIdeaForm(i=null,isExisting=true){els.ideaForm.reset();const existing=isExisting&&i?.IdeaID;els.ideaId.value=existing?i.IdeaID:'';els.ideaDialogTitle.textContent=existing?'Edit idea':'Idea details';els.ideaTitle.value=i?.Title||'';els.ideaSummary.value=i?.OneLineSummary||'';els.ideaStage.value=i?.Stage||'Idea';els.ideaPriority.value=i?.Priority||'Medium';els.ideaOwner.value=i?.OwnerUserID||state.user.userId;els.ideaCategory.value=i?.Category||'';els.ideaTags.value=i?.Tags||'';els.ideaDescription.value=i?.Description||'';els.ideaProblem.value=i?.Problem||'';els.ideaSolution.value=i?.ProposedSolution||'';els.ideaTargetUser.value=i?.TargetUser||'';els.ideaWhy.value=i?.WhyItCouldWork||'';els.ideaNextAction.value=i?.NextAction||'';els.ideaNextOwner.value=i?.NextActionOwner||'';els.ideaNextDue.value=i?.NextActionDue||'';els.ideaDialog.showModal();setTimeout(()=>els.ideaTitle.focus(),40);}
  async function saveIdea(e){e.preventDefault();const id=els.ideaId.value,data={title:els.ideaTitle.value.trim(),oneLineSummary:els.ideaSummary.value.trim(),stage:els.ideaStage.value,priority:els.ideaPriority.value,ownerUserId:els.ideaOwner.value,category:els.ideaCategory.value.trim(),tags:els.ideaTags.value.trim(),description:els.ideaDescription.value.trim(),problem:els.ideaProblem.value.trim(),proposedSolution:els.ideaSolution.value.trim(),targetUser:els.ideaTargetUser.value.trim(),whyItCouldWork:els.ideaWhy.value.trim(),nextAction:els.ideaNextAction.value.trim(),nextActionOwner:els.ideaNextOwner.value,nextActionDue:els.ideaNextDue.value};if(!data.title)return;busy(els.saveIdeaButton,true,'Saving…');try{let created=null;if(id){data.ideaId=id;await api('updateIdea',data);}else{data.status='Draft';created=await api('createIdea',data);}els.ideaDialog.close();await refresh();toast(id?'Idea updated':'Idea saved');if(!id&&created?.idea?.IdeaID)openIdea(created.idea.IdeaID,'rating');}catch(err){toast('Could not save idea',err.message,'error');}finally{busy(els.saveIdeaButton,false);}}

  async function openIdea(id,tab='overview'){state.currentIdea=null;state.currentIdeaData=null;state.currentTab=tab;els.ideaDetailRoot.innerHTML='<div class="modal-body"><p style="color:var(--faint)">Loading…</p></div>';els.detailDialog.showModal();try{const p=await api('getIdea',{ideaId:id}),d=p.idea||{},i=d.idea||d;state.currentIdea=i;state.currentIdeaData=d;renderIdeaDetail();}catch(err){els.ideaDetailRoot.innerHTML=`<div class="modal-body">${empty('Could not load idea',err.message)}</div>`;}}
  function detailTabs(){return[['overview','Overview'],['brainstorm','Discussion'],['rating','Rating'],['validation','Validation'],['planning','Plan'],['execution','Execute'],['media','Media']];}
  function renderIdeaDetail(){const i=state.currentIdea,d=state.currentIdeaData;if(!i||!d)return;const u=userById(i.OwnerUserID),c=u?.accentColor||'#5869f6',score=combinedScore(i.IdeaID);els.ideaDetailRoot.innerHTML=`<div class="detail-shell"><button class="icon-button detail-close" data-close-detail>${icon.close}</button><div class="detail-hero"><div class="detail-meta"><span class="stage-chip">${esc(workflowStatus(i))}</span><span class="pill" style="color:${c}">${esc(u?.displayName||'Unknown')}</span>${i.Category?`<span class="pill">${esc(i.Category)}</span>`:''}</div><div class="detail-title-row"><div><h2>${esc(i.Title)}</h2><p>${esc(i.OneLineSummary||'')}</p></div><div class="detail-score-block ${pulseClass(i)}"><strong>${score==null?'—':score.toFixed(1)}</strong><span>Combined score</span></div></div></div><div class="detail-tabs">${detailTabs().map(([k,label])=>`<button class="detail-tab ${state.currentTab===k?'active':''}" data-detail-tab="${k}">${label}</button>`).join('')}</div><div id="detailContent" class="detail-content">${renderDetailTab()}</div><div class="detail-actions"><button class="button button-danger button-small" data-archive-idea>Archive</button><div class="detail-action-right"><button class="button button-secondary button-small" data-rate-current>Rate idea</button><button class="button button-secondary button-small" data-edit-current>Edit</button></div></div></div>`;bindDetailEvents();afterDetailRender();}
  function renderDetailTab(){const i=state.currentIdea,d=state.currentIdeaData;switch(state.currentTab){case'brainstorm':return brainstormTab(i,d);case'rating':return ratingTab(i,d);case'validation':return validationTab(i,d);case'planning':return planningTab(i,d);case'execution':return executionTab(i,d);case'media':return mediaTab(i,d);default:return overviewTab(i,d);}}
  function overviewTab(i){return`<div class="detail-grid"><div class="info-card full"><h4>Notes</h4><p>${esc(i.Description||'No notes yet.')}</p></div><div class="info-card"><h4>Problem</h4><p>${esc(i.Problem||'Not defined')}</p></div><div class="info-card"><h4>Proposed solution</h4><p>${esc(i.ProposedSolution||'Not defined')}</p></div><div class="info-card"><h4>Target user</h4><p>${esc(i.TargetUser||'Not defined')}</p></div><div class="info-card"><h4>Why it could work</h4><p>${esc(i.WhyItCouldWork||'Not defined')}</p></div><div class="info-card full"><h4>Next action</h4><p>${esc(i.NextAction||'No next action')}${i.NextActionDue?`\nDue ${fmtDate(i.NextActionDue)}`:''}</p></div></div>`;}
  function brainstormTab(i,d){const notes=d.brainstorm||[],comments=d.comments||[];return`<div class="discussion-grid"><section><h3 class="section-title">Brainstorm notes</h3><div class="stack">${notes.length?notes.slice().reverse().map(n=>`<div class="note-card"><strong>${esc(profileName(n.UserID))}</strong><p>${esc(n.Content)}</p></div>`).join(''):'<p style="color:var(--faint);font-size:10px">No notes yet.</p>'}</div><div class="inline-form"><label class="field"><span>Add note</span><textarea id="brainstormInput" rows="3"></textarea></label><button id="addBrainstormBtn" class="button button-primary button-small">Add note</button></div></section><section><h3 class="section-title">Discussion</h3><div class="stack">${comments.length?comments.slice().reverse().map(c=>`<div class="comment-card"><strong>${esc(profileName(c.UserID))}</strong><p>${esc(c.Comment)}</p><small style="color:var(--faint)">${esc(fmtDate(c.CreatedAt,true))}</small></div>`).join(''):'<p style="color:var(--faint);font-size:10px">No comments yet.</p>'}</div><div class="inline-form"><label class="field"><span>Add comment</span><textarea id="commentInput" rows="3"></textarea></label><button id="addCommentBtn" class="button button-primary button-small">Add comment</button></div></section></div>`;}
  function workflowPanel(i,mine){const status=String(i.Status||'Draft'),isOwner=i.OwnerUserID===state.user.userId,isReviewer=i.CoOwnerUserID===state.user.userId,other=otherMember();if(i.Stage!=='Idea')return'';if(isOwner&&['','Active','Draft','Needs Work'].includes(status)){return`<div class="workflow-panel"><div><span class="eyebrow">Next step</span><h3>${status==='Needs Work'?'Update and resubmit':'Send for review'}</h3><p>${mine?`Your rating is saved. Send this idea to ${esc(other?.displayName||'the other member')} for an independent review.`:'Rate your idea first. Once your self-rating is saved, you can send it for review.'}</p></div>${mine?'<button id="sendForReviewBtn" class="button button-primary">Send for review</button>':''}</div>`;}if(status==='Awaiting Review'){if(isReviewer)return`<div class="workflow-panel"><div><span class="eyebrow">Review requested</span><h3>Your decision</h3><p>${mine?'Your rating is saved. Choose what should happen next.':'Rate the idea first, then choose a decision.'}</p></div>${mine?'<div class="workflow-actions"><button class="button button-primary" data-review-decision="Proceed">Proceed</button><button class="button button-secondary" data-review-decision="Needs work">Needs work</button><button class="button button-danger" data-review-decision="Park">Park</button></div>':''}</div>`;return`<div class="workflow-panel waiting"><div><span class="eyebrow">Awaiting review</span><h3>Waiting for ${esc(profileName(i.CoOwnerUserID))}</h3><p>You can still edit the idea while the review is pending.</p></div></div>`;}if(status==='Approved'&&isOwner)return`<div class="workflow-panel approved"><div><span class="eyebrow">Approved</span><h3>Ready for planning</h3><p>The review is complete. Move this idea into Planning when you want to turn it into responsibilities and actions.</p></div><button id="movePlanningBtn" class="button button-primary">Move to Planning</button></div>`;return'';}
  function ratingTab(i){const users=state.profiles.map(p=>p.user||p),mine=ratingFor(i.IdeaID,state.user.userId),combined=combinedScore(i.IdeaID);return`<div class="rating-summary"><div class="big-score"><strong>${round1(combined)}</strong><span>Combined score</span></div><div><table class="rating-table"><thead><tr><th>Criteria</th>${users.map(u=>`<th>${esc(u.displayName)}</th>`).join('')}</tr></thead><tbody>${CRITERIA.map(([k,label])=>`<tr><td>${esc(label)}</td>${users.map(u=>`<td>${ratingFor(i.IdeaID,u.userId)?.[k]||'—'}</td>`).join('')}</tr>`).join('')}<tr><td><strong>Overall</strong></td>${users.map(u=>`<td><strong>${round1(ratingScore(ratingFor(i.IdeaID,u.userId)))}</strong></td>`).join('')}</tr></tbody></table></div></div><div class="inline-form rating-form" style="margin-top:16px"><h3 class="section-title">${mine?'Your rating':'Rate this idea'}</h3><div class="rating-input-grid">${CRITERIA.map(([k,label])=>`<div class="rating-control"><label>${esc(label)}</label><select data-rating-field="${k}">${Array.from({length:10},(_,x)=>x+1).map(v=>`<option value="${v}" ${(mine?.[k]||8)==v?'selected':''}>${v}</option>`).join('')}</select></div>`).join('')}</div><label class="field" style="margin-top:12px"><span>Note</span><textarea id="ratingNotes" rows="3">${esc(mine?.notes||'')}</textarea></label><button id="saveRatingBtn" class="button button-primary button-small">${mine?'Update rating':'Save rating'}</button></div>${workflowPanel(i,mine)}`;}
  function validationTab(i,d){const ex=d.experiments||[];return`<h3 class="section-title">Experiments</h3><div class="stack">${ex.length?ex.map(e=>`<div class="experiment-card"><div style="display:flex;justify-content:space-between;gap:8px"><strong>${esc(e.Title||'Experiment')}</strong><span class="pill">${esc(e.Status||'Planned')}</span></div><p>${esc(e.Assumption||'')}</p>${e.SuccessCriteria?`<p><strong>Success:</strong> ${esc(e.SuccessCriteria)}</p>`:''}${e.Result?`<p><strong>Result:</strong> ${esc(e.Result)}</p>`:''}</div>`).join(''):'<p style="color:var(--faint);font-size:10px">No experiments yet.</p>'}</div><div class="inline-form"><h3 class="section-title">Add experiment</h3><div class="inline-form-grid"><label class="field field-span"><span>Title</span><input id="expTitle"></label><label class="field field-span"><span>Assumption</span><textarea id="expAssumption" rows="2"></textarea></label><label class="field"><span>Test method</span><textarea id="expMethod" rows="2"></textarea></label><label class="field"><span>Success criteria</span><textarea id="expSuccess" rows="2"></textarea></label></div><button id="addExperimentBtn" class="button button-primary button-small">Add experiment</button></div>`;}
  function planningTab(i,d){const tasks=d.tasks||[];return`<div class="detail-grid"><div class="info-card"><h4>Problem</h4><p>${esc(i.Problem||'Not defined')}</p></div><div class="info-card"><h4>Target user</h4><p>${esc(i.TargetUser||'Not defined')}</p></div><div class="info-card"><h4>Solution</h4><p>${esc(i.ProposedSolution||'Not defined')}</p></div><div class="info-card"><h4>Why it could work</h4><p>${esc(i.WhyItCouldWork||'Not defined')}</p></div></div><div class="inline-form" style="margin-top:14px"><h3 class="section-title">Next action</h3><div class="inline-form-grid"><label class="field field-span"><span>Action</span><input id="planNextAction" value="${esc(i.NextAction||'')}"></label><label class="field"><span>Owner</span><select id="planNextOwner"><option value="">Not assigned</option>${state.profiles.map(p=>{const u=p.user||p;return`<option value="${esc(u.userId)}" ${i.NextActionOwner===u.userId?'selected':''}>${esc(u.displayName||u.fullName)}</option>`}).join('')}</select></label><label class="field"><span>Due</span><input id="planNextDue" type="date" value="${esc(i.NextActionDue||'')}"></label></div><button id="savePlanBtn" class="button button-primary button-small">Save plan</button></div><section class="responsibility-section"><div class="section-simple-head"><h3>Responsibilities</h3></div><div class="planning-task-list">${tasks.length?tasks.map(t=>`<article class="planning-task"><div><strong>${esc(t.Title)}</strong><span>${esc(profileName(t.OwnerUserID))}${t.DueDate?` · ${esc(fmtDate(t.DueDate))}`:''}</span></div><select data-task-status="${esc(t.TaskID)}">${TASK_STATUSES.map(x=>`<option ${x===t.Status?'selected':''}>${x}</option>`).join('')}</select></article>`).join(''):'<p class="quiet-copy">No responsibilities assigned yet.</p>'}</div><div class="inline-form"><div class="inline-form-grid"><label class="field field-span"><span>Responsibility</span><input id="taskTitle"></label><label class="field"><span>Owner</span><select id="taskOwner">${state.profiles.map(p=>{const u=p.user||p;return`<option value="${esc(u.userId)}" ${u.userId===state.user.userId?'selected':''}>${esc(u.displayName||u.fullName)}</option>`}).join('')}</select></label><label class="field"><span>Due</span><input id="taskDue" type="date"></label></div><button id="addTaskBtn" class="button button-primary button-small">Add responsibility</button></div></section>${i.Stage==='Planning'?'<div class="stage-action"><button id="startExecutionBtn" class="button button-primary">Start execution</button></div>':''}`;}
  function executionTab(i,d){const tasks=d.tasks||[];return`<div class="task-board">${TASK_STATUSES.map(status=>`<section class="task-column"><h4>${status}</h4>${tasks.filter(t=>t.Status===status).map(t=>`<div class="task-card"><strong>${esc(t.Title)}</strong><p>${esc(t.Description||'')}</p><small>${esc(profileName(t.OwnerUserID))}${t.DueDate?` · ${esc(fmtDate(t.DueDate))}`:''}</small><select data-task-status="${esc(t.TaskID)}">${TASK_STATUSES.map(s=>`<option ${s===t.Status?'selected':''}>${s}</option>`).join('')}</select></div>`).join('')||'<p style="color:var(--faint);font-size:9px">No tasks</p>'}</section>`).join('')}</div><div class="inline-form"><h3 class="section-title">Add responsibility</h3><div class="inline-form-grid"><label class="field field-span"><span>Task</span><input id="taskTitle"></label><label class="field"><span>Owner</span><select id="taskOwner">${state.profiles.map(p=>{const u=p.user||p;return`<option value="${esc(u.userId)}" ${u.userId===state.user.userId?'selected':''}>${esc(u.displayName||u.fullName)}</option>`}).join('')}</select></label><label class="field"><span>Due</span><input id="taskDue" type="date"></label></div><button id="addTaskBtn" class="button button-primary button-small">Add responsibility</button></div>${i.Status!=='Completed'?'<div class="stage-action"><button id="completeIdeaBtn" class="button button-primary">Mark idea completed</button></div>':'<div class="completed-banner">Completed</div>'}`;}
  function mediaTab(i,d){const at=d.attachments||[];return`<div style="display:flex;justify-content:flex-end;margin-bottom:12px"><button id="attachMediaBtn" class="button button-secondary button-small">${icon.plus} Attach media</button><input id="attachmentInput" type="file" multiple hidden accept="image/*,video/*,audio/*,.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt,.zip"></div>${at.length?`<div class="media-grid">${at.map(a=>`<article class="media-card" data-preview-attachment="${esc(a.AttachmentID)}" data-drive-url="${esc(a.DriveURL||'')}"><div class="media-thumb" data-thumb="${esc(a.AttachmentID)}">${String(a.MimeType||'').startsWith('image/')?icon.image:icon.file}</div><strong>${esc(a.FileName||'Attachment')}</strong><div class="media-meta">${esc([a.MimeType,bytes(a.SizeBytes)].filter(Boolean).join(' · '))}</div></article>`).join('')}</div>`:'<p style="color:var(--faint);font-size:10px">No media attached.</p>'}`;}

  function bindDetailEvents(){one('[data-close-detail]',els.ideaDetailRoot)?.addEventListener('click',()=>els.detailDialog.close());qsa('[data-detail-tab]',els.ideaDetailRoot).forEach(b=>b.addEventListener('click',()=>{state.currentTab=b.dataset.detailTab;renderIdeaDetail();}));one('[data-edit-current]',els.ideaDetailRoot)?.addEventListener('click',()=>{els.detailDialog.close();openIdeaForm(state.currentIdea,true);});one('[data-rate-current]',els.ideaDetailRoot)?.addEventListener('click',()=>{state.currentTab='rating';renderIdeaDetail();});one('[data-archive-idea]',els.ideaDetailRoot)?.addEventListener('click',()=>archiveIdea(state.currentIdea.IdeaID));}
  function afterDetailRender(){const i=state.currentIdea;if(!i)return;$('addBrainstormBtn')?.addEventListener('click',()=>addBrainstorm(i.IdeaID));$('addCommentBtn')?.addEventListener('click',()=>addComment(i.IdeaID));$('saveRatingBtn')?.addEventListener('click',()=>saveRating(i.IdeaID));$('sendForReviewBtn')?.addEventListener('click',()=>sendForReview(i.IdeaID));qsa('[data-review-decision]',els.ideaDetailRoot).forEach(b=>b.addEventListener('click',()=>reviewDecision(i.IdeaID,b.dataset.reviewDecision)));$('movePlanningBtn')?.addEventListener('click',()=>moveToPlanning(i.IdeaID));$('startExecutionBtn')?.addEventListener('click',()=>startExecution(i.IdeaID));$('completeIdeaBtn')?.addEventListener('click',()=>completeIdea(i.IdeaID));$('addExperimentBtn')?.addEventListener('click',()=>addExperiment(i.IdeaID));$('savePlanBtn')?.addEventListener('click',()=>savePlan(i.IdeaID));$('addTaskBtn')?.addEventListener('click',()=>addTask(i.IdeaID));qsa('[data-task-status]',els.ideaDetailRoot).forEach(s=>s.addEventListener('change',()=>updateTaskStatus(i.IdeaID,s.dataset.taskStatus,s.value)));$('attachMediaBtn')?.addEventListener('click',()=>$('attachmentInput')?.click());$('attachmentInput')?.addEventListener('change',e=>uploadAttachments(i.IdeaID,e.target.files));qsa('[data-preview-attachment]',els.ideaDetailRoot).forEach(c=>c.addEventListener('click',()=>previewAttachment(c.dataset.previewAttachment,c.dataset.driveUrl)));if(state.currentTab==='media')hydrateMediaThumbnails();}
  async function reloadCurrentIdea(tab=state.currentTab){const id=state.currentIdea.IdeaID;const p=await api('getIdea',{ideaId:id});state.currentIdeaData=p.idea||{};state.currentIdea=state.currentIdeaData.idea||state.currentIdeaData;state.currentTab=tab;renderIdeaDetail();}
  async function addBrainstorm(ideaId){const v=$('brainstormInput')?.value.trim();if(!v)return;const b=$('addBrainstormBtn');busy(b,true,'Adding…');try{await api('addBrainstorm',{ideaId,content:v,noteType:'Note'});await reloadCurrentIdea('brainstorm');toast('Note added');}catch(e){toast('Could not add note',e.message,'error');}finally{busy(b,false);}}
  async function addComment(ideaId){const v=$('commentInput')?.value.trim();if(!v)return;const b=$('addCommentBtn');busy(b,true,'Adding…');try{await api('addComment',{ideaId,comment:v,targetType:'Idea',targetId:ideaId});await reloadCurrentIdea('brainstorm');toast('Comment added');}catch(e){toast('Could not add comment',e.message,'error');}finally{busy(b,false);}}
  async function saveRating(ideaId){const b=$('saveRatingBtn'),data={ideaId,notes:$('ratingNotes')?.value.trim()||''};qsa('[data-rating-field]',els.ideaDetailRoot).forEach(s=>data[s.dataset.ratingField]=Number(s.value));busy(b,true,'Saving…');try{await insights('saveRating',data);const p=await insights('listRatings');state.ratings=p.ratings||[];renderIdeaDetail();renderCurrent();toast('Rating saved');}catch(e){toast('Could not save rating',e.message,'error');}finally{busy(b,false);}}
  async function sendForReview(ideaId){const other=otherMember();if(!other){toast('Reviewer unavailable','A second active member is required.','error');return;}if(!ratingFor(ideaId,state.user.userId)){toast('Rate your idea first','Save your self-rating before sending it for review.','error');return;}const b=$('sendForReviewBtn');busy(b,true,'Sending…');try{await api('updateIdea',{ideaId,coOwnerUserId:other.userId,status:'Awaiting Review'});await refresh(false);await reloadCurrentIdea('rating');toast('Sent for review',`${other.displayName||other.fullName} can now review the idea.`);}catch(e){toast('Could not send for review',e.message,'error');}finally{busy(b,false);}}
  async function reviewDecision(ideaId,decision){const mine=ratingFor(ideaId,state.user.userId);if(!mine){toast('Rate the idea first','Save your rating before choosing a decision.','error');return;}try{await insights('saveReviewDecision',{ideaId,decision});if(decision==='Park'){await api('archiveIdea',{ideaId});els.detailDialog.close();await refresh();toast('Idea parked');navigate('ideas');return;}await api('updateIdea',{ideaId,status:decision==='Proceed'?'Approved':'Needs Work'});await refresh(false);await reloadCurrentIdea('rating');toast(decision==='Proceed'?'Idea approved':'Sent back for changes');}catch(e){toast('Could not save review',e.message,'error');}}
  async function moveToPlanning(ideaId){const b=$('movePlanningBtn');busy(b,true,'Moving…');try{await api('updateIdea',{ideaId,stage:'Planning',status:'Active'});await refresh(false);await reloadCurrentIdea('planning');toast('Moved to Planning');}catch(e){toast('Could not move idea',e.message,'error');}finally{busy(b,false);}}
  async function startExecution(ideaId){const b=$('startExecutionBtn');busy(b,true,'Starting…');try{await api('updateIdea',{ideaId,stage:'Execution',status:'Active'});await refresh(false);await reloadCurrentIdea('execution');toast('Execution started');}catch(e){toast('Could not start execution',e.message,'error');}finally{busy(b,false);}}
  async function completeIdea(ideaId){const b=$('completeIdeaBtn');busy(b,true,'Completing…');try{await api('updateIdea',{ideaId,status:'Completed'});await refresh(false);await reloadCurrentIdea('execution');toast('Idea completed');}catch(e){toast('Could not complete idea',e.message,'error');}finally{busy(b,false);}}
  async function addExperiment(ideaId){const title=$('expTitle')?.value.trim();if(!title)return;const b=$('addExperimentBtn');busy(b,true,'Adding…');try{await api('createExperiment',{ideaId,title,assumption:$('expAssumption').value.trim(),testMethod:$('expMethod').value.trim(),successCriteria:$('expSuccess').value.trim(),ownerUserId:state.user.userId,status:'Planned'});await reloadCurrentIdea('validation');toast('Experiment added');}catch(e){toast('Could not add experiment',e.message,'error');}finally{busy(b,false);}}
  async function savePlan(ideaId){const b=$('savePlanBtn');busy(b,true,'Saving…');try{await api('updateIdea',{ideaId,nextAction:$('planNextAction').value.trim(),nextActionOwner:$('planNextOwner').value,nextActionDue:$('planNextDue').value});await refresh(false);await reloadCurrentIdea('planning');toast('Plan saved');}catch(e){toast('Could not save plan',e.message,'error');}finally{busy(b,false);}}
  async function addTask(ideaId){const title=$('taskTitle')?.value.trim();if(!title)return;const b=$('addTaskBtn');busy(b,true,'Adding…');try{await api('createTask',{ideaId,title,ownerUserId:$('taskOwner').value,dueDate:$('taskDue').value,status:'To Do',priority:'Medium'});await refresh(false);await reloadCurrentIdea(state.currentTab);toast('Responsibility added');}catch(e){toast('Could not add task',e.message,'error');}finally{busy(b,false);}}
  async function updateTaskStatus(ideaId,taskId,status){try{await api('updateTask',{taskId,status});await refresh(false);await reloadCurrentIdea(state.currentTab);}catch(e){toast('Could not update task',e.message,'error');}}
  function fileToBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=()=>reject(new Error('Could not read the selected file.'));r.readAsDataURL(file);});}
  async function uploadAttachments(ideaId,list){const files=Array.from(list||[]);if(!files.length)return;const max=10*1024*1024,tooLarge=files.find(f=>f.size>max);if(tooLarge){toast('File too large','Maximum file size is 10 MB.','error');return;}const b=$('attachMediaBtn');busy(b,true,'Uploading…');try{for(const f of files){await api('uploadAttachment',{ideaId,fileName:f.name,mimeType:f.type||'application/octet-stream',base64:await fileToBase64(f)});}await reloadCurrentIdea('media');toast(files.length===1?'File attached':`${files.length} files attached`);}catch(e){toast('Upload failed',e.message,'error');}finally{busy(b,false);}}
  async function hydrateMediaThumbnails(){const at=(state.currentIdeaData?.attachments||[]).filter(a=>String(a.MimeType||'').startsWith('image/')).slice(0,8);await Promise.allSettled(at.map(async a=>{try{const p=await api('getAttachmentData',{attachmentId:a.AttachmentID});const x=p.attachment;if(!x?.base64||x.tooLarge)return;const root=one(`[data-thumb="${CSS.escape(a.AttachmentID)}"]`,els.ideaDetailRoot);if(root)root.innerHTML=`<img alt="${esc(a.FileName||'Image')}" src="data:${esc(a.MimeType||'image/jpeg')};base64,${x.base64}">`;}catch{}}));}
  async function previewAttachment(id,driveUrl){const a=(state.currentIdeaData?.attachments||[]).find(x=>x.AttachmentID===id);if(!a)return;const mime=String(a.MimeType||'');if(!mime.startsWith('image/')&&!mime.startsWith('video/')&&!mime.startsWith('audio/')){if(driveUrl)window.open(driveUrl,'_blank','noopener');return;}els.mediaTitle.textContent=a.FileName||'Media';els.mediaPreviewRoot.innerHTML='<p style="color:#cbd0dc">Loading…</p>';els.mediaDialog.showModal();try{const p=await api('getAttachmentData',{attachmentId:id}),x=p.attachment;if(x.tooLarge||!x.base64){els.mediaDialog.close();if(driveUrl)window.open(driveUrl,'_blank','noopener');return;}const src=`data:${mime||'application/octet-stream'};base64,${x.base64}`;if(mime.startsWith('image/'))els.mediaPreviewRoot.innerHTML=`<img src="${src}" alt="${esc(a.FileName||'Image')}">`;else if(mime.startsWith('video/'))els.mediaPreviewRoot.innerHTML=`<video src="${src}" controls autoplay></video>`;else els.mediaPreviewRoot.innerHTML=`<audio src="${src}" controls autoplay></audio>`;}catch(e){els.mediaDialog.close();if(driveUrl)window.open(driveUrl,'_blank','noopener');}}
  async function archiveIdea(ideaId){if(!confirm('Archive this idea?'))return;try{await api('archiveIdea',{ideaId});els.detailDialog.close();await refresh();toast('Idea archived');}catch(e){toast('Could not archive idea',e.message,'error');}}

  function openSearch(){els.globalSearch.value='';renderSearch('');els.searchDialog.showModal();setTimeout(()=>els.globalSearch.focus(),40);}
  function renderSearch(q){q=String(q||'').trim().toLowerCase();const rows=state.ideas.filter(i=>!q||[i.Title,i.OneLineSummary,i.Description,i.Category,i.Tags].join(' ').toLowerCase().includes(q)).slice(0,15);els.searchResults.innerHTML=rows.length?rows.map(ideaRow).join(''):'<div style="padding:24px;text-align:center;color:var(--faint);font-size:10px">No matching ideas.</div>';bindRendered(els.searchResults);}
  function bindRendered(root){qsa('[data-open-idea]',root).forEach(x=>x.addEventListener('click',e=>{if(e.defaultPrevented)return;openIdea(x.dataset.openIdea);}));qsa('[data-nav-inline]',root).forEach(x=>x.addEventListener('click',()=>navigate(x.dataset.navInline)));qsa('[data-new-idea]',root).forEach(x=>x.addEventListener('click',openQuickIdea));qsa('[data-change-avatar]',root).forEach(x=>x.addEventListener('click',openAvatarPicker));qsa('[data-idea-view]',root).forEach(x=>x.addEventListener('click',()=>{state.ideaView=x.dataset.ideaView;localStorage.setItem(VIEW_KEY,state.ideaView);renderIdeas();}));}

  function bindStatic(){
    els.loginForm.addEventListener('submit',login);els.quickIdeaForm.addEventListener('submit',saveQuickIdea);els.quickMoreDetails.addEventListener('click',quickToDetails);els.ideaForm.addEventListener('submit',saveIdea);els.passwordForm.addEventListener('submit',changePassword);els.logoutButton.addEventListener('click',logout);els.openPasswordButton.addEventListener('click',()=>{els.profileMenu.hidden=true;els.passwordForm.reset();els.passwordError.hidden=true;els.passwordDialog.showModal();});
    els.searchButton.addEventListener('click',openSearch);els.topAddIdea.addEventListener('click',openQuickIdea);els.saveCustomAvatar.addEventListener('click',()=>saveAvatar(els.customAvatarInput.value));els.globalSearch.addEventListener('input',e=>renderSearch(e.target.value));els.sidebarOpen.addEventListener('click',openSidebar);els.sidebarClose.addEventListener('click',closeSidebar);els.sidebarCollapse.addEventListener('click',toggleSidebar);els.sidebarScrim.addEventListener('click',closeSidebar);els.profileMenuButton.addEventListener('click',()=>{els.profileMenu.hidden=!els.profileMenu.hidden;});
    qsa('[data-nav]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();navigate(b.dataset.nav);}));qsa('[data-close-dialog]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.closeDialog)?.close()));qsa('[data-password-toggle]').forEach(b=>b.addEventListener('click',()=>{const i=$(b.dataset.passwordToggle);if(i)i.type=i.type==='password'?'text':'password';}));
    [els.quickIdeaDialog,els.ideaDialog,els.detailDialog,els.searchDialog,els.avatarDialog,els.passwordDialog,els.mediaDialog].forEach(d=>d?.addEventListener('click',e=>{if(e.target===d)d.close();}));
    document.addEventListener('keydown',e=>{const tag=document.activeElement?.tagName?.toLowerCase(),typing=['input','textarea','select'].includes(tag);if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(!els.appView.hidden)openSearch();return;}if(!typing&&!e.ctrlKey&&!e.metaKey&&e.key.toLowerCase()==='n'){e.preventDefault();if(!els.appView.hidden)openQuickIdea();}if(!typing&&!e.ctrlKey&&!e.metaKey&&e.key==='/'){e.preventDefault();if(!els.appView.hidden)openSearch();}if(e.key==='Escape')closeSidebar();});
  }

  async function boot(){setSidebarCollapsed(localStorage.getItem(SIDEBAR_KEY)==='1');bindStatic();if(!state.token){showLogin();return;}try{await loadState();showApp();navigate('home');}catch(e){console.warn(e);clearSession(true);}}
  boot();
})();
