from pathlib import Path
import re

p=Path('app.js')
s=p.read_text(encoding='utf-8')

old="    dragIdeaId:'', workItems:[], workFilter:'mine', analyticsFilters:{owner:'all',stage:'all',category:'all',score:'all',flow:'all'}"
new="    dragIdeaId:'', workItems:[], workFilter:'mine', reviewSessions:[], weeklyReview:null, analyticsFilters:{owner:'all',stage:'all',category:'all',score:'all',flow:'all'}"
if old not in s:
    raise SystemExit('state marker not found')
s=s.replace(old,new,1)

pat=re.compile(r"  function renderReviews\(\)\{.*?\n\n  function analyticsIdeas",re.S)
block=r'''  function weeklyReviewQueue(){
    const weight=i=>i.Stage==='Execution'?0:i.Stage==='Planning'?1:i.Status==='Approved'?2:i.Status==='Needs Work'?3:i.Status==='Awaiting Review'?4:5;
    return state.ideas.filter(i=>!['Archived','Completed'].includes(String(i.Status||''))).slice().sort((a,b)=>weight(a)-weight(b)||String(b.LastActivityAt||b.UpdatedAt||'').localeCompare(String(a.LastActivityAt||a.UpdatedAt||'')));
  }
  function parseReviewSummary(value){try{const x=JSON.parse(String(value||''));return x&&x.v===1?x:{v:1,queue:[],items:[]};}catch{return{v:1,queue:[],items:[]};}}
  function reviewSummaryPayload(){const w=state.weeklyReview||{};return JSON.stringify({v:1,queue:w.queue||[],items:w.items||[]});}
  function reviewDecisionOptions(i){
    if(i.Stage==='Execution')return['Continue execution','Complete','Park'];
    if(i.Stage==='Planning')return['Continue planning','Start execution','Park'];
    if(i.Status==='Approved')return['Keep approved','Move to planning','Park'];
    if(i.Status==='Needs Work')return['Continue refining','Park'];
    if(i.Status==='Awaiting Review')return['Keep pending review','Park'];
    return['Keep in ideas','Park'];
  }
  function reviewScorePair(i){return state.profiles.map(p=>{const u=p.user||p,s=ratingScore(ratingFor(i.IdeaID,u.userId));return`<span class="weekly-person-score">${ownerAvatar(u.userId)}<span><small>${esc(u.displayName||u.fullName)}</small><strong>${round1(s)}</strong></span></span>`}).join('');}
  function renderReviews(){
    if(state.weeklyReview)return state.weeklyReview.completed?renderWeeklyReviewSummary():renderWeeklyReviewWorkspace();
    const gaps=state.ideas.map(i=>({idea:i,gap:ratingGap(i.IdeaID),score:combinedScore(i.IdeaID)})).filter(x=>x.gap!=null).sort((a,b)=>b.gap-a.gap).slice(0,6),unrated=state.ideas.filter(i=>ratingsForIdea(i.IdeaID).length<state.profiles.length).slice(0,6),active=weeklyReviewQueue();
    wrap(`<div class="weekly-review-home"><section class="review-start-card"><div><span class="eyebrow">Weekly review</span><h2>Review the active portfolio</h2><p>${active.length} active ${active.length===1?'idea':'ideas'} available for this review.</p></div><button id="newReviewBtn" class="button button-primary">${icon.plus} Start review</button></section><div class="review-grid"><div><div class="review-card"><h3>Review sessions</h3><div id="reviewSessions"><p style="color:var(--faint);font-size:10px">Loading…</p></div></div><div class="review-card" style="margin-top:14px"><h3>Largest rating gaps</h3>${gaps.length?gaps.map(x=>`<div class="review-session" data-open-idea="${esc(x.idea.IdeaID)}"><span><strong>${esc(x.idea.Title)}</strong><small>Combined ${round1(x.score)}</small></span><span class="score-badge">${x.gap.toFixed(1)} gap</span></div>`).join(''):'<p style="color:var(--faint);font-size:10px">No paired ratings yet.</p>'}</div></div><aside class="review-card"><h3>Needs a rating</h3>${unrated.length?unrated.map(i=>`<div class="review-session" data-open-idea="${esc(i.IdeaID)}"><span><strong>${esc(i.Title)}</strong><small>${ratingsForIdea(i.IdeaID).length}/${state.profiles.length} rated</small></span><span class="stage-chip">${esc(workflowStatus(i))}</span></div>`).join(''):'<p style="color:var(--faint);font-size:10px">All active ideas are rated.</p>'}</aside></div></div>`);
    $('newReviewBtn')?.addEventListener('click',createReview);loadReviews();
  }
  async function loadReviews(){const root=$('reviewSessions');if(!root)return;try{const p=await api('listReviewSessions'),rows=(p.reviewSessions||[]).slice().reverse().slice(0,12);state.reviewSessions=rows;root.innerHTML=rows.length?rows.map(r=>`<button class="review-session review-session-button" data-review-session="${esc(r.ReviewSessionID)}"><span><strong>${esc(r.Title)}</strong><small>${esc(r.Status)} · ${esc(r.ReviewDate)}</small></span><span class="pill">${r.Status==='In Progress'?'Resume':'View'}</span></button>`).join(''):'<p style="color:var(--faint);font-size:10px;margin-top:12px">No review sessions yet.</p>';qsa('[data-review-session]',root).forEach(b=>b.addEventListener('click',()=>openReviewSession(b.dataset.reviewSession)));}catch(e){root.innerHTML=`<p style="color:var(--red);font-size:10px">${esc(e.message)}</p>`;}}
  }
  async function createReview(){const b=$('newReviewBtn'),queue=weeklyReviewQueue();if(!queue.length){toast('Nothing to review','There are no active ideas right now.');return;}busy(b,true,'Starting…');try{const p=await api('createReviewSession',{status:'In Progress',startedAt:new Date().toISOString()}),session=p.reviewSession;state.weeklyReview={session,queue:queue.map(i=>i.IdeaID),items:[],index:0,completed:false};await api('updateReviewSession',{reviewSessionId:session.ReviewSessionID,summary:reviewSummaryPayload()});renderWeeklyReviewWorkspace();}catch(e){toast('Could not start review',e.message,'error');}finally{busy(b,false);}}
  function openReviewSession(id){const session=state.reviewSessions.find(r=>r.ReviewSessionID===id);if(!session)return;const saved=parseReviewSummary(session.Summary),queue=(saved.queue||[]).length?saved.queue:weeklyReviewQueue().map(i=>i.IdeaID),items=saved.items||[],done=new Set(items.map(x=>x.ideaId)),index=queue.findIndex(x=>!done.has(x));state.weeklyReview={session,queue,items,index:index<0?queue.length:index,completed:session.Status==='Completed'};renderCurrent();}
  function backToReviewList(){state.weeklyReview=null;renderReviews();}
  function currentWeeklyIdea(){const w=state.weeklyReview;if(!w||w.index>=w.queue.length)return null;return state.ideas.find(i=>i.IdeaID===w.queue[w.index])||null;}
  function renderWeeklyReviewWorkspace(){const w=state.weeklyReview;if(!w)return renderReviews();let i=currentWeeklyIdea();while(!i&&w.index<w.queue.length){w.index++;i=currentWeeklyIdea();}if(!i)return renderWeeklyReviewFinish();const completed=w.items.length,total=w.queue.length,score=combinedScore(i.IdeaID),opts=reviewDecisionOptions(i),ownerOpts=state.profiles.map(p=>{const u=p.user||p;return`<option value="${esc(u.userId)}" ${u.userId===state.user.userId?'selected':''}>${esc(u.displayName||u.fullName)}</option>`}).join('');wrap(`<div class="review-workspace"><div class="review-workspace-head"><button id="backReviewList" class="button button-secondary button-small">Back to reviews</button><div class="review-progress-copy"><span>Weekly review</span><strong>${completed+1} of ${total}</strong></div><div class="review-progress-track"><span style="width:${total?Math.round(completed/total*100):0}%"></span></div></div><article class="review-focus-card"><div class="review-focus-top"><div><span class="stage-chip">${esc(workflowStatus(i))}</span><h2>${esc(i.Title)}</h2><p>${esc(i.OneLineSummary||i.Description||'No summary')}</p></div><div class="review-score-large"><strong>${round1(score)}</strong><span>Combined</span></div></div><div class="weekly-score-pair">${reviewScorePair(i)}</div><div class="review-context-grid"><div><span>Owner</span><strong>${esc(profileName(i.OwnerUserID))}</strong></div><div><span>Current next action</span><strong>${esc(i.NextAction||'None')}</strong></div><div><span>Due</span><strong>${esc(i.NextActionDue?fmtDate(i.NextActionDue):'Not set')}</strong></div></div><div class="weekly-decision-form"><label class="field"><span>Decision</span><select id="weeklyDecision">${opts.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label class="field"><span>Next action</span><input id="weeklyNextAction" maxlength="500" placeholder="Optional action from this review"></label><div class="inline-form-grid"><label class="field"><span>Owner</span><select id="weeklyActionOwner">${ownerOpts}</select></label><label class="field"><span>Due date</span><input id="weeklyActionDue" type="date"></label></div></div><div class="review-step-actions"><button id="skipWeeklyIdea" class="button button-secondary">Skip</button><button id="saveWeeklyIdea" class="button button-primary">Save & next</button></div></article></div>`);$('backReviewList')?.addEventListener('click',backToReviewList);$('skipWeeklyIdea')?.addEventListener('click',skipWeeklyReviewItem);$('saveWeeklyIdea')?.addEventListener('click',saveWeeklyReviewItem);}
  async function persistWeeklyProgress(){const w=state.weeklyReview;if(!w)return;await api('updateReviewSession',{reviewSessionId:w.session.ReviewSessionID,summary:reviewSummaryPayload()});}
  async function skipWeeklyReviewItem(){const w=state.weeklyReview,i=currentWeeklyIdea();if(!w||!i)return;const b=$('skipWeeklyIdea');busy(b,true,'Skipping…');try{await api('addScore',{reviewSessionId:w.session.ReviewSessionID,ideaId:i.IdeaID,decision:'Skipped',nextAction:''});w.items.push({ideaId:i.IdeaID,title:i.Title,decision:'Skipped',nextAction:'',ownerUserId:'',dueDate:'',stage:i.Stage,score:combinedScore(i.IdeaID)});w.index++;await persistWeeklyProgress();renderWeeklyReviewWorkspace();}catch(e){toast('Could not skip idea',e.message,'error');}finally{busy(b,false);}}
  async function saveWeeklyReviewItem(){const w=state.weeklyReview,i=currentWeeklyIdea();if(!w||!i)return;const b=$('saveWeeklyIdea'),decision=$('weeklyDecision')?.value||'',nextAction=$('weeklyNextAction')?.value.trim()||'',ownerUserId=$('weeklyActionOwner')?.value||'',dueDate=$('weeklyActionDue')?.value||'';busy(b,true,'Saving…');try{await api('addScore',{reviewSessionId:w.session.ReviewSessionID,ideaId:i.IdeaID,decision,nextAction});let resultingStage=i.Stage,taskId='';if(decision==='Park'){await api('archiveIdea',{ideaId:i.IdeaID});}else{const update={ideaId:i.IdeaID};if(decision==='Move to planning'){update.stage='Planning';update.status='Active';resultingStage='Planning';}if(decision==='Start execution'){update.stage='Execution';update.status='Active';resultingStage='Execution';}if(decision==='Complete'){update.status='Completed';}if(nextAction){update.nextAction=nextAction;update.nextActionOwner=ownerUserId;update.nextActionDue=dueDate;}if(Object.keys(update).length>1)await api('updateIdea',update);if(nextAction&&ownerUserId&&['Planning','Execution'].includes(resultingStage)&&decision!=='Complete'){const t=await api('createTask',{ideaId:i.IdeaID,title:nextAction,ownerUserId,dueDate,status:'To Do',priority:i.Priority||'Medium'});taskId=t.task?.TaskID||'';}}w.items.push({ideaId:i.IdeaID,title:i.Title,decision,nextAction,ownerUserId,dueDate,stage:resultingStage,score:combinedScore(i.IdeaID),taskId});w.index++;await persistWeeklyProgress();await refresh(false);renderWeeklyReviewWorkspace();}catch(e){toast('Could not save review decision',e.message,'error');}finally{busy(b,false);}}
  function renderWeeklyReviewFinish(){const w=state.weeklyReview;if(!w)return;wrap(`<div class="review-finish"><div class="review-finish-head"><span class="eyebrow">Review complete</span><h2>${w.items.length} ${w.items.length===1?'idea':'ideas'} reviewed</h2><p>Check the decisions below, then finish the session.</p></div>${weeklyReviewItemsHTML(w.items)}<div class="review-finish-actions"><button id="backReviewList" class="button button-secondary">Back to reviews</button><button id="finishWeeklyReview" class="button button-primary">Finish review</button></div></div>`);$('backReviewList')?.addEventListener('click',backToReviewList);$('finishWeeklyReview')?.addEventListener('click',finishWeeklyReview);}
  function weeklyReviewItemsHTML(items){return`<div class="review-summary-list">${items.map(x=>`<article class="review-summary-item"><div><span class="stage-chip">${esc(x.stage||'Idea')}</span><strong>${esc(x.title)}</strong>${x.nextAction?`<p>${esc(x.nextAction)}${x.ownerUserId?` · ${esc(profileName(x.ownerUserId))}`:''}${x.dueDate?` · ${esc(fmtDate(x.dueDate))}`:''}</p>`:''}</div><span class="review-decision-pill">${esc(x.decision)}</span></article>`).join('')}</div>`;}
  async function finishWeeklyReview(){const w=state.weeklyReview;if(!w)return;const b=$('finishWeeklyReview');busy(b,true,'Finishing…');try{const t=new Date().toISOString();const p=await api('updateReviewSession',{reviewSessionId:w.session.ReviewSessionID,status:'Completed',completedAt:t,summary:reviewSummaryPayload()});w.session=p.reviewSession||{...w.session,Status:'Completed',CompletedAt:t};w.completed=true;renderWeeklyReviewSummary();toast('Weekly review completed');}catch(e){toast('Could not finish review',e.message,'error');}finally{busy(b,false);}}
  function renderWeeklyReviewSummary(){const w=state.weeklyReview;if(!w)return renderReviews();const moved=w.items.filter(x=>x.decision==='Move to planning').length,started=w.items.filter(x=>x.decision==='Start execution').length,completed=w.items.filter(x=>x.decision==='Complete').length,actions=w.items.filter(x=>x.nextAction).length;wrap(`<div class="review-finish completed"><div class="review-finish-head"><button id="backReviewList" class="button button-secondary button-small">Back to reviews</button><span class="eyebrow">Completed weekly review</span><h2>${esc(w.session.Title||'Weekly review')}</h2><p>${esc(w.session.ReviewDate||'')}</p></div><div class="review-summary-metrics"><div><strong>${w.items.length}</strong><span>Reviewed</span></div><div><strong>${actions}</strong><span>Actions</span></div><div><strong>${moved+started}</strong><span>Moved forward</span></div><div><strong>${completed}</strong><span>Completed</span></div></div>${weeklyReviewItemsHTML(w.items)}</div>`);$('backReviewList')?.addEventListener('click',backToReviewList);}

  function analyticsIdeas'''
s,n=pat.subn(block,s,count=1)
if n!=1:
    raise SystemExit('review block not found')
p.write_text(s,encoding='utf-8')

p=Path('styles.css')
s=p.read_text(encoding='utf-8')
css=r'''

/* Weekly review workspace */
.weekly-review-home{display:grid;gap:16px}.review-start-card{padding:24px 26px;border:1px solid rgba(109,124,157,.14);border-radius:22px;display:flex;align-items:center;justify-content:space-between;gap:24px;background:linear-gradient(135deg,rgba(255,255,255,.88),rgba(240,245,255,.82));box-shadow:0 14px 38px rgba(48,62,95,.06)}.review-start-card h2{margin:3px 0 6px;font:800 27px/1.08 var(--display);letter-spacing:-.04em}.review-start-card p{margin:0;color:var(--sub);font-size:11px}.review-session-button{width:100%;border:0;background:transparent;text-align:left;cursor:pointer}.review-session-button:hover{background:var(--soft)}
.review-workspace{max-width:980px;margin:0 auto}.review-workspace-head{display:grid;grid-template-columns:auto auto 1fr;align-items:center;gap:15px;margin-bottom:18px}.review-progress-copy{display:grid}.review-progress-copy span{color:var(--faint);font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:.1em}.review-progress-copy strong{font-size:12px}.review-progress-track{height:5px;border-radius:999px;background:#e6ebf4;overflow:hidden}.review-progress-track span{display:block;height:100%;border-radius:inherit;background:linear-gradient(90deg,#566fe8,#7b8cf2);transition:width .25s ease}.review-focus-card{padding:28px;border:1px solid rgba(105,120,155,.14);border-radius:25px;background:rgba(255,255,255,.88);box-shadow:0 22px 60px rgba(43,58,91,.08)}.review-focus-top{display:flex;align-items:flex-start;justify-content:space-between;gap:30px}.review-focus-top h2{margin:10px 0 7px;font:800 clamp(25px,3vw,35px)/1.05 var(--display);letter-spacing:-.045em}.review-focus-top p{max-width:700px;margin:0;color:var(--sub);font-size:12px}.review-score-large{width:96px;height:96px;flex:0 0 auto;border-radius:30px;display:grid;place-items:center;align-content:center;background:#182035;color:#fff;box-shadow:0 16px 36px rgba(24,32,53,.16)}.review-score-large strong{font:800 30px/1 var(--display)}.review-score-large span{margin-top:6px;color:rgba(255,255,255,.55);font-size:8px}.weekly-score-pair{display:flex;gap:10px;flex-wrap:wrap;margin:22px 0}.weekly-person-score{min-width:150px;padding:10px 12px;border-radius:15px;display:flex;align-items:center;gap:9px;background:#f0f4fb}.weekly-person-score>span:last-child{display:grid}.weekly-person-score small{color:var(--faint);font-size:8px}.weekly-person-score strong{font:800 15px var(--display)}.review-context-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-bottom:18px}.review-context-grid>div{padding:12px 13px;border-radius:14px;background:#f5f7fb}.review-context-grid span{display:block;color:var(--faint);font-size:8px;font-weight:700;text-transform:uppercase;letter-spacing:.07em}.review-context-grid strong{display:block;margin-top:5px;font-size:10px}.weekly-decision-form{padding:18px;border-radius:18px;background:#f2f5fa}.review-step-actions{display:flex;justify-content:space-between;gap:10px;margin-top:18px}.review-step-actions .button-primary{min-width:140px}
.review-finish{max-width:980px;margin:0 auto}.review-finish-head{margin-bottom:20px}.review-finish-head h2{margin:5px 0 6px;font:800 30px/1.08 var(--display);letter-spacing:-.045em}.review-finish-head p{margin:0;color:var(--sub);font-size:11px}.review-summary-list{display:grid;gap:9px}.review-summary-item{padding:14px 16px;border:1px solid rgba(105,120,155,.12);border-radius:16px;display:flex;align-items:center;justify-content:space-between;gap:20px;background:rgba(255,255,255,.82)}.review-summary-item>div{min-width:0}.review-summary-item strong{display:block;margin-top:6px;font-size:12px}.review-summary-item p{margin:4px 0 0;color:var(--sub);font-size:9px}.review-decision-pill{flex:0 0 auto;padding:6px 9px;border-radius:999px;background:#e8eefc;color:#445da9;font-size:9px;font-weight:800}.review-finish-actions{display:flex;justify-content:space-between;margin-top:18px}.review-summary-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-bottom:16px}.review-summary-metrics>div{padding:15px;border-radius:16px;background:#eef3fb}.review-summary-metrics strong{display:block;font:800 22px var(--display)}.review-summary-metrics span{display:block;margin-top:2px;color:var(--faint);font-size:8px;font-weight:700}
@media(max-width:700px){.review-start-card,.review-focus-top{display:block}.review-start-card .button{margin-top:16px}.review-score-large{margin-top:18px}.review-workspace-head{grid-template-columns:auto 1fr}.review-progress-track{grid-column:1/-1}.review-context-grid,.review-summary-metrics{grid-template-columns:1fr 1fr}.review-summary-item{align-items:flex-start}.review-step-actions{position:sticky;bottom:10px;padding:10px;border-radius:15px;background:rgba(248,250,255,.92);backdrop-filter:blur(12px)}}
'''
if '/* Weekly review workspace */' not in s:
    s+=css
p.write_text(s,encoding='utf-8')
